name: "Test HTTP Service Satisfies Specification"

on:
  workflow_call:
    inputs:
      image:
        description: "Name (which is also the path) of the Image to test"
        required: true
        type: string

jobs:
  http-fixtures:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to GitHub Container Registry as actor
        uses: docker/login-action@v1
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ github.token }}"
      - name: Get commit hash
        id: commit
        uses: pr-mpt/actions-commit-hash@v1
        with:
          prefix: "sha-"
      - name: Launch test service(s)
        env:
          COMPOSE_FILE: "./${{ inputs.image }}/docker-compose.tests.yaml"
          SPARSE_IMAGE: "ghcr.io/${{ github.repository }}-${{ inputs.image }}:${{ steps.commit.outputs.short }}"
        run: |
          docker compose pull --ignore-pull-failures
          docker compose up -d --wait
      ##################################################
      # The greeting fixture is available on port 8080 #
      ##################################################
      - name: Perform index page request to greeting
        id: greeting-index-response
        uses: CamiloGarciaLaRotta/watermelon-http-client@v1
        with:
          url: "http://localhost:8080"
      - name: Load greeting fixture
        id: greeting-index-expected
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.github/workflows/fixtures/greeting/expected.html
      - name: Test greeting index page matches fixture
        uses: pr-mpt/actions-assert@v3
        with:
          assertion: npm://@assertions/equivalent-html:v1
          actual: "${{ fromJSON(steps.greeting-index-response.outputs.response) }}"
          expected: "${{ steps.greeting-index-expected.outputs.content }}"
