name: "Test HTTP Service Satisfies Specification"

on:
  workflow_call:
    inputs:
      path:
        description: "Path to the directory containing the docker compose tests configuration"
        required: true
        type: string
        default: "."

jobs:
  http-fixtures:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Launch test service(s)
        run: docker compose -f ./${{ inputs.path }}/docker-compose.tests.yaml up -d --wait
      ##################################################
      # The greeting fixture is available on port 8080 #
      ##################################################
      - name: Perform index page request to greeting
        id: greeting-index-response
        uses: CamiloGarciaLaRotta/watermelon-http-client@v1
        with:
          url: "http://localhost:8080"
      - name: Load greeting fixture
        id: greeting-index-expected
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.github/workflows/fixtures/greeting/expected.html
      - name: Test greeting index page matches fixture
        uses: pr-mpt/actions-assert@v3
        with:
          assertion: npm://@assertions/is-equal:v1
          actual: "${{ steps.greeting-index-response.outputs.response }}"
          expected: "${{ steps.greeting-index-expected.outputs.content }}"
